export const LOAD_POPULAR_TRACKS = 'LOAD_POPULAR_TRACKS';
export const LOAD_POPULAR_TRACKS_SUCCESS = 'LOAD_POPULAR_TRACKS_SUCCESS';
export const LOAD_POPULAR_TRACKS_FAILURE = 'LOAD_POPULAR_TRACKS_FAILURE';