export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
//Auth
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
//
export const ADD_OBJECT_ID_TO_FORMDATA = 'ADD_OBJECT_ID_TO_FORMDATA';
export const REMOVE_OBJECT_ID_TO_FORMDATA = 'REMOVE_OBJECT_ID_TO_FORMDATA';
export const CLEAR_OBJECT_IDS = 'CLEAR_OBJECT_IDS';
export const ADD_MASTER_TRACK_REF = 'ADD_MASTER_TRACK_REF';
export const REMOVE_MASTER_TRACK_REF = 'REMOVE_MASTER_TRACK_REF';
//
export const EDIT_ADD_OBJECT_ID_TO_FORMDATA = 'EDIT_ADD_OBJECT_ID_TO_FORMDATA';
export const EDIT_REMOVE_OBJECT_ID_TO_FORMDATA = 'EDIT_REMOVE_OBJECT_ID_TO_FORMDATA';
export const EDIT_CLEAR_OBJECT_IDS = 'EDIT_CLEAR_OBJECT_IDS';
// Notifications
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_DISMISS = 'NOTIFICATION_DISMISS';
export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';
// Create User
export const SET_COUNTRY = 'SET_COUNTRY';
export const RESET_COUNTRY = 'RESET_COUNTRY';

//addition - Trupti - Wits
export const SET_COMPANY = 'SET_COMPANY';
export const RESET_COMPANY = 'RESET_COMPANY';
