export const LOAD_RECENTLY_ADDED_TRACKS = 'LOAD_RECENTLY_ADDED_TRACKS';
export const LOAD_RECENTLY_ADDED_TRACKS_SUCCESS = 'LOAD_RECENTLY_ADDED_TRACKS_SUCCESS';
export const LOAD_RECENTLY_ADDED_TRACKS_FAILURE = 'LOAD_RECENTLY_ADDED_TRACKS_FAILURE';