export const LOAD_CURATED_PLAYLISTS = 'LOAD_CURATED_PLAYLISTS';
export const LOAD_CURATED_PLAYLISTS_SUCCESS = 'LOAD_CURATED_PLAYLISTS_SUCCESS';
export const LOAD_CURATED_PLAYLISTS_FAILURE = 'LOAD_CURATED_PLAYLISTS_FAILURE';