//addition by Trupti-Wits

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
//Auth
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const ADD_MFA_META = "ADD_MFA_META";
export const REMOVE_MFA_META = "REMOVE_MFA_META";
export const SET_USER_META = "SET_USER_META";
export const RESET_USER_META = "RESET_USER_META";

//Player
export const SET_IS_PLAYING_INDEX = "SET_IS_PLAYING_INDEX";
export const SET_IS_FOOTER_MUSIC_PLAYER_PLAYING =
  "SET_IS_FOOTER_MUSIC_PLAYER_PLAYING";

//Search
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const SET_RESULTS_FOR = "SET_RESULTS_FOR";
export const SET_REFINEMENT_ITEMS = "SET_REFINEMENT_ITEMS";
export const SET_SEARCH_STATE = "SET_SEARCH_STATE";
export const CLEAR_SEARCH_ATTRIBUTES = "CLEAR_SEARCH_ATTRIBUTES";
export const SET_SEARCH_URL = "SET_SEARCH_URL";
export const SET_DROPDOWN_STATE = "SET_DROPDOWN_STATE";
//Layout
export const TOGGLE_NEWSEARCH_DIALOG = "TOGGLE_NEWSEARCH_DIALOG";
export const SET_DEVICE_TYPE = "SET_DEVICE_TYPE";

// Notifications
export const NOTIFICATION_SHOW = "NOTIFICATION_SHOW";
export const NOTIFICATION_DISMISS = "NOTIFICATION_DISMISS";
export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";
export const SET_NOTIFICATION_TOP_BAR = "SET_NOTIFICATION_TOP_BAR";
export const RESET_NOTIFICATION_TOP_BAR = "RESET_NOTIFICATION_TOP_BAR";
//Playlist
export const GET_PLAYLIST_BY_ID = "GET_PLAYLIST_BY_ID";
export const GET_PLAYLIST_DATA_UNREGISTERED = "GET_PLAYLIST_DATA_UNREGISTERED";
export const GET_ALL_PLAYLISTS = "GET_ALL_PLAYLISTS";
export const OPEN_DELETE_PLAYLISTDIALOG = "OPEN_DELETE_PLAYLISTDIALOG";
export const CLOSE_DELETE_PLAYLISTDIALOG = "CLOSE_DELETE_PLAYLISTDIALOG";

export const OPEN_SHARETABS_PLAYLISTDIALOG = "OPEN_SHARETABS_PLAYLISTDIALOG";
export const CLOSE_SHARETABS_PLAYLISTDIALOG = "CLOSE_SHARETABS_PLAYLISTDIALOG";

export const OPEN_CREATE_NEW_PLAYLISTDIALOG = "OPEN_CREATE_NEW_PLAYLISTDIALOG";
export const CLOSE_CREATE_NEW_PLAYLISTDIALOG =
  "CLOSE_CREATE_NEW_PLAYLISTDIALOG";
export const GET_PLAYLISTDATA_SUCESS = "GET_PLAYLISTDATA_SUCESS";
export const GET_PLAYLISTDATA_BY_ID_SUCCESS = "GET_PLAYLISTDATA_BY_ID_SUCCESS";
export const START_FETCHING_PLAYLIST_BY_ID_DATA =
  "START_FETCHING_PLAYLIST_BY_ID_DATA";
export const START_FETCHING_PLAYLIST_META = "START_FETCHING_PLAYLIST_META";
export const SET_CREATE_NEW_PLAYLIST_TYPE = "SET_CREATE_NEW_PLAYLIST_TYPE";
export const CREATE_NEW_PLAYLIST_WITH_TRACK_ID =
  "CREATE_NEW_PLAYLIST_WITH_TRACK_ID";
export const PLAYLIST_DOES_NOT_EXIST = "PLAYLIST_DOES_NOT_EXIST";

// PLAYLIST - MEMBERS
//SearchUser
export const SEARCH_FOR_USER = "SEARCH_FOR_USER";
export const OPEN_SEARCH_MEMBER_DIALOG = "OPEN_SEARCH_MEMBER_DIALOG";
export const CLOSE_SEARCH_MEMBER_DIALOG = "CLOSE_SEARCH_MEMBER_DIALOG";
export const OPEN_SEARCH_MEMBER_EXTERNAL_DIALOG =
  "OPEN_SEARCH_MEMBER_EXTERNAL_DIALOG";
export const CLOSE_SEARCH_MEMBER_EXTERNAL_DIALOG =
  "CLOSE_SEARCH_MEMBER_EXTERNAL_DIALOG";
export const OPEN_MEMBER_OVERVIEW_DIALOG = "OPEN_MEMBER_OVERVIEW_DIALOG";
export const CLOSE_MEMBER_OVERVIEW_DIALOG = "CLOSE_MEMBER_OVERVIEW_DIALOG";
export const OPEN_MEMBER_OVERVIEW_GUEST_DIALOG =
  "OPEN_MEMBER_OVERVIEW_GUEST_DIALOG";
export const CLOSE_MEMBER_OVERVIEW_GUEST_DIALOG =
  "CLOSE_MEMBER_OVERVIEW_GUEST_DIALOG";
export const UPDATE_MEMBER_IDS_FORM = "UPDATE_MEMBER_IDS_FORM";
export const CLEAR_MEMBER_IDS_FROM_FORM = "CLEAR_MEMBER_IDS_FROM_FORM";

export const UPDATE_MEMBER_EXT_IDS_FORM = "UPDATE_MEMBER_EXT_IDS_FORM";

export const UPDATE_MEMBER_COMBINE_IDS_FORM = "UPDATE_MEMBER_COMBINE_IDS_FORM";

// PLAYLIST - COMMENTS
export const GET_ALL_COMMENTS_BY_PLAYLIST_ID =
  "GET_ALL_COMMENTS_BY_PLAYLIST_ID";
export const GET_ALL_COMMENTS_BY_PLAYLIST_ID_AND_TIMESTAMP =
  "GET_ALL_COMMENTS_BY_PLAYLIST_ID_AND_TIMESTAMP";
export const START_FETCHING_COMMENTS = "START_FETCHING_COMMENTS";
export const END_FETCHING_COMMENTS = "END_FETCHING_COMMENTS";

// JOBHISTORY
export const SET_JOBHISTORY_IDS = "SET_JOBHISTORY_IDS";
export const SET_JOBHISTORY_PROCCESSED_DATA = "SET_JOBHISTORY_PROCCESSED_DATA";
export const REMOVE_ALL_JOBHISTORY_PROCCESSED_DATA =
  "REMOVE_ALL_JOBHISTORY_PROCCESSED_DATA";
export const SET_IS_GET_JOBHISTORY_STATUS_LOOPED =
  "SET_IS_GET_JOBHISTORY_STATUS_LOOPED";
export const SET_TTS_VOICES = "SET_TTS_VOICES";

// Download Cart
export const SET_INIT_DOWNLOAD_BASKET = "SET_INIT_DOWNLOAD_BASKET";
export const ADD_TO_DOWNLOAD_BASKET = "ADD_TO_DOWNLOAD_BASKET";
export const ADD_BATCH_TO_DOWNLOAD_BASKET = "ADD_BATCH_TO_DOWNLOAD_BASKET";
export const RESET_TRACK_DOWNLOADING_PROCESS =
  "RESET_TRACK_DOWNLOADING_PROCESS";
export const SET_DOWNLOAD_BASKET_META = "SET_DOWNLOAD_BASKET_META";
export const RESET_DOWNLOAD_BASKET_META = "RESET_DOWNLOAD_BASKET_META";
export const ADD_PLAYLIST_TO_DOWNLOAD_BASKET =
  "ADD_PLAYLIST_TO_DOWNLOAD_BASKET";
export const REMOVE_SELECTED_TRACK_FROM_DOWNLOAD_BASKET =
  "REMOVE_SELECTED_TRACK_FROM_DOWNLOAD_BASKET";
export const REMOVE_DOWNLOADED_TRACKS_AND_RESET_DOWNLOAD_PROCESS =
  "REMOVE_DOWNLOADED_TRACKS_AND_RESET_DOWNLOAD_PROCESS";

// fav track ids
export const SET_FAV_TRACK_ID = "SET_FAV_TRACK_ID";
export const REMOVE_FAV_TRACK_ID = "REMOVE_FAV_TRACK_ID";
export const SET_ALL_FAV_TRACK_IDS = "SET_ALL_FAV_TRACK_IDS";
export const SET_SIMIL_QUERY = "SET_SIMIL_QUERY";
export const SET_CYANITE_IDSMGT = "SET_CYANITE_IDSMGT";
// taxonomy tags
export const ADD_ASSET_TYPES = "ADD_ASSET_TYPES";
export const ADD_AMP_MAIN_MOOD_TAGS = "ADD_AMP_MAIN_MOOD_TAGS";
export const ADD_AMP_MOOD_TAGS = "ADD_AMP_MOOD_TAGS";
export const ADD_SONIC_LOGO_MAIN_MOOD_TAGS = "ADD_SONIC_LOGO_MAIN_MOOD_TAGS";
export const ADD_SONIC_LOGO_MOOD_TAGS = "ADD_SONIC_LOGO_MOOD_TAGS";
export const ADD_INSTRUMENTS = "ADD_INSTRUMENTS";
export const ADD_TRACK_TYPES = "ADD_TRACK_TYPES";
//Report Modal
export const OPEN_CLOSE_REPORT_MODAL = "OPEN_CLOSE_REPORT_MODAL";

// Common msg modal
export const SET_COMMON_MESSAGE = "SET_COMMON_MESSAGE";
export const RESET_COMMON_MESSAGE = "RESET_COMMON_MESSAGE";
export const SET_IS_OPEN_COMMON_MESSAGE_MODAL =
  "SET_IS_OPEN_COMMON_MESSAGE_MODAL";

//config json
export const SET_CONFIG_JSON = "SET_CONFIG_JSON";
export const RESET_CONFIG_JSON = "RESET_CONFIG_JSON";

export const SET_TRACK_FILTERS = "SET_TRACK_FILTERS";
export const RESET_TRACK_FILTERS = "RESET_TRACK_FILTERS";
export const SET_TRACK_TYPE_FILTERS = "SET_TRACK_TYPE_FILTERS";
export const RESET_TRACK_TYPE_FILTERS = "RESET_TRACK_TYPE_FILTERS";
export const RESET_ALL_TRACK_FILTERS = "RESET_ALL_TRACK_FILTERS";
export const UPDATE_SUPERSEARCH_TRACK_FILTERS =
  "UPDATE_SUPERSEARCH_TRACK_FILTERS";

export const SET_SUPERSEARCH_TRACK_FILTERS = "SET_SUPERSEARCH_TRACK_FILTERS";
export const RESET_SUPERSEARCH_TRACK_FILTERS =
  "RESET_SUPERSEARCH_TRACK_FILTERS";

// video upload actions type
export const SET_VIDEO_UPLOAD = "SET_VIDEO_UPLOAD";
export const RESET_VIDEO_UPLOAD = "RESET_VIDEO_UPLOAD";

//Breif store
export const SET_AI_MUSIC_GENERATOR = "SET_AI_MUSIC_GENERATOR";
export const RESET_AI_MUSIC_GENERATOR = "RESET_AI_MUSIC_GENERATOR";

//CUSTOM_TRACK_FORM
export const SET_CUSTOM_TRACK_FORM = "SET_CUSTOM_TRACK_FORM";
export const RESET_CUSTOM_TRACK_FORM = "RESET_CUSTOM_TRACK_FORM";

// Tracnsaction Token
export const SET_TRANSACTION_TOKEN = "SET_TRANSACTION_TOKEN";
//MUSIC_LICENSING_FORM
export const SET_MUSIC_LICENSING_FORM = "SET_MUSIC_LICENSING_FORM";
export const RESET_MUSIC_LICENSING_FORM = "RESET_MUSIC_LICENSING_FORM";
// Predict data
export const SET_PREDICT = "SET_PREDICT";
export const CLEAR_PREDICT = "CLEAR_PREDICT";
